### ISSUE TITLE
Install incomplete (qtpyvcp_conversational_gcode-main)

### ISSUE THREAD

**Issue by ferrumd** [kcjengr/probe_basic#69]
when trying to install it fails whilst installing "qtpyvcp_conversational_gcode-main"
`Traceback (most recent call last):
  File "./setup.py", line 1, in <module>
    import versioneer
  File "/home/dgentile/Downloads/qtpyvcp_conversational_gcode-main/versioneer.py", line 418
    LONG_VERSION_PY: Dict[str, str] = {}
                   ^
SyntaxError: invalid syntax
`

**Comment by hasechris** [comment]
just want to second this. Sadly now im stuck with a non-functioning cnc machine.

**Comment by TurBoss** [comment]
conversational gcode got  integradted into probe basic

no need to install it anymore

**Comment by Alexfehr1987** [comment]
same issue for me. old 2.8.4 didn't boot anymore, tried debian 12 but it was totally instable on my machine. then tried to install "old"-working 2.8.4 but probebasic is not working there anymore because of conversational error....now i have a nonworking cnc

**Comment by Lcvette** [comment]
This version is no longer available or supported, newer python3 version are resolved
